SSID = 'ACxxxxxxxxxxxxxxxxxxxxc57463a55789' #You can find SSID in your Twilio Dashboard
AUTH_TOKEN = 'dfxxxxxxxxxxxxxxxxxxxx27ae7407ac' #You can find SSID in your Twilio Dashboard
FROM_NUMBER = '+1224xxxxxx0' #This is the no. generated by Twilio. You can find this on your Twilio Dashboard
TO_NUMBER = '+9172xxxxxxx1' #This is your number. Make sure you are adding +91 in beginning
API_KEY = '0c64xxxx-xxxx-xxxx-xxxx-xxxxxxxxx66a' #This is Bolt Cloud account API key
DEVICE_ID = 'BOLTxxxxx4' #This is the ID of Bolt device
FRAME_SIZE = 20 #the number of previous data points the used to predict the trend of the data Anomality.
MUL_FACTOR = 5 #It is propotional to z-score. Increasing/decreasing it will Increase/Decrease threshold.